export const APP_CATALOG = [
  { id: 'telegram', icon: 'send' },
  { id: 'notion', icon: 'book-open' },
  { id: 'figma', icon: 'layers' },
  { id: 'trello', icon: 'columns-3' },
  { id: 'slack', icon: 'message-square' },
  { id: 'zoom', icon: 'video' },
  { id: 'stripe', icon: 'credit-card' },
  { id: 'gmail', icon: 'mail' },
  { id: 'medium', icon: 'book-open' },
  { id: 'skype', icon: 'phone' },
  { id: 'docker', icon: 'box' },
  { id: 'github', icon: 'github' },
  { id: 'gitlab', icon: 'git-branch' },
  { id: 'discord', icon: 'message-circle' },
  { id: 'whatsapp', icon: 'message-square' },
];